version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
    labels:
      - dependencies
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
    labels:
      - dependencies
    groups:
      npm-minor:
        applies-to: version-updates
        update-types: ['minor', 'patch']
        patterns: ['*']

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
    labels:
      - dependencies
    groups:
      cargo-minor:
        applies-to: version-updates
        update-types: ['minor', 'patch']
        patterns: ['*']
